create table employees (id int8 generated by default as identity, avatar varchar(255), description varchar(255), job_id int8, likes_count int4, location_id int8, name varchar(255), primary key (id));
create table feedback (id int8 generated by default as identity, email varchar(255), message varchar(255), name varchar(255), primary key (id));
create table jobs (id int8 generated by default as identity, name varchar(255), primary key (id));
create table location (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists employees add constraint FKnpqyu6u0fdh2rmqtoue23gxb4 foreign key (job_id) references jobs;
alter table if exists employees add constraint FKfunpcpviyq9sykks0t0fkw1u6 foreign key (location_id) references location;
